require:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-sorbet

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Sorbet/StrictSigil:
  Enabled: true
  Exclude:
    - 'test/**/*'

Sorbet/TrueSigil:
  Enabled: true
  Include:
    - 'test/**/*'