require:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-sorbet

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Sorbet/StrictSigil:
  Enabled: true
  Exclude:
    - 'test/**/*'

Sorbet/FalseSigil:
  Enabled: true
  Include:
    - 'test/**/*'