# typed: strict
# frozen_string_literal: true

module LobbyingDisclosureClient
  module Enums
    class GeneralIssueCode < T::Enum
      enums do
        Acc = new('ACC')
        Adv = new('ADV')
        Aer = new('AER')
        Agr = new('AGR')
        Alc = new('ALC')
        Ani = new('ANI')
        App = new('APP')
        Art = new('ART')
        Aut = new('AUT')
        Avi = new('AVI')
        Ban = new('BAN')
        Bnk = new('BNK')
        Bev = new('BEV')
        Bud = new('BUD')
        Civ = new('CIV')
        Chm = new('CHM')
        Caw = new('CAW')
        Cdt = new('CDT')
        Com = new('COM')
        Cpi = new('CPI')
        Con = new('CON')
        Csp = new('CSP')
        Cpt = new('CPT')
        Def = new('DEF')
        Dis = new('DIS')
        Doc = new('DOC')
        Ecn = new('ECN')
        Edu = new('EDU')
        Eng = new('ENG')
        Env = new('ENV')
        Fam = new('FAM')
        Fin = new('FIN')
        Fir = new('FIR')
        Foo = new('FOO')
        For = new('FOR')
        Fue = new('FUE')
        Gam = new('GAM')
        Gov = new('GOV')
        Hcr = new('HCR')
        Hom = new('HOM')
        Hou = new('HOU')
        Imm = new('IMM')
        Ind = new('IND')
        Ins = new('INS')
        Int = new('INT')
        Lbr = new('LBR')
        Law = new('LAW')
        Man = new('MAN')
        Mar = new('MAR')
        Mia = new('MIA')
        Med = new('MED')
        Mmm = new('MMM')
        Mon = new('MON')
        Nat = new('NAT')
        Pha = new('PHA')
        Pos = new('POS')
        Rrr = new('RRR')
        Res = new('RES')
        Rel = new('REL')
        Ret = new('RET')
        Rod = new('ROD')
        Sci = new('SCI')
        Smb = new('SMB')
        Spo = new('SPO')
        Tar = new('TAR')
        Tax = new('TAX')
        Tec = new('TEC')
        Tob = new('TOB')
        Tor = new('TOR')
        Trd = new('TRD')
        Tra = new('TRA')
        Tou = new('TOU')
        Tru = new('TRU')
        Urb = new('URB')
        Unm = new('UNM')
        Uti = new('UTI')
        Vet = new('VET')
        Was = new('WAS')
        Wel = new('WEL')
      end
    end
  end
end
