name: Sorbet
on: [push, pull_request]
jobs:
  sorbet:
    name: Sorbet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec srb tc